### ISSUE TITLE
Extract Tables form the Tom Competency Framework PDF and upload them in csv

### ISSUE THREAD

**Issue by PilarRius** [FAOEuFMD/TOM-Recommender-System#1]
Extract Tables form the Tom Competency Framework PDF and upload them in csv.
PDF TOM Competency Framework can be found at the project files drive. 
Use Python to extract the tables you can use a package called pdfplumber or explore others. 
Once done upload the csv file in this repo and communicate it to the team.

First column: Competency (1 to 14 title on the page) second column is level : use text only Awareness etc.., third column will be behaviour and must one by one

**Comment by amanisakif** [comment]
Done
